services:
  db:
    image: mariadb:10.11
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: personaldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/personaldb
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin1234
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - backend

  node:
    image: node:22
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm install && npm run start"
    ports:
      - "8000:3000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin1234
      DB_NAME: personaldb
      PORT_SERVER: 3000
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
